name: Build CloudStream Plugins

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: gradle:8.10.2-jdk17
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build plugins
        run: gradle make --stacktrace
      - name: Upload builds
        uses: actions/upload-artifact@v4
        with:
          name: cloudstream-plugins
          path: "**/build/*.cs3"
          if-no-files-found: error
